---
editor_options: 
  markdown: 
    wrap: 72
---

# Tilgátuprófun

Þegar við setjum upp rannsóknir eða söfnum gögnum þá höfum við
einhverjar spurningar í huga sem við viljum leitast svara við.

**Tilgátuprófun** er það ferli að setja spurninguna okkar fram í formi
tilgáta og nota viðeigandi tölfræðipróf til að fá einfalt já/nei við
spurningunni okkar eftir því hvort niðurstöður reynist marktækar eða
ómarktækar.

Tilgátuprófun svarar spurningunni **hvort það sé munur** \-- í kjölfarið
viljum við auðvitað vita **hve miklu munar** og notum þá spá, þar sem
úrtakstölur eru notaðar til að spá fyrir um þýðisgildin. Augljóst
vandamál er að tölfræðiforrit skilja ekki setningar - við gætum ekki
beinlínis sett gögn inn í úrvinnslu ásamt spurningunni "eru mánaðarlaun
ólík eftir menntun fólks?".

Það má því ímynda sér ferlið í grófum dráttum á eftirfarandi hátt: Við
yfirfærum spurninguna okkar yfir á *tölfræðilegt form* sem forritið
skilur og segjum því hvaða tölfræðiaðferð það eigi að nota við að svara
spurningunni okkar. Forritið vinnur úr gögnunum fyrir okkur og spýtir út
úr sér niðurstöðum. Þessar niðurstöður eru þá enn á *tölfræðilegu formi*
og það er okkar verk að skilja hvað niðurstöðurnar segja okkur og geta
gefið túlkun sem setur þær aftur á *mannamál*.

## Tilgátur {#cross}

Við byrjum á því að setja fram **tilgátur**. Í okkar dæmi viljum við
vita hvort það sé munur á launum einstaklings eftir menntun viðkomandi.

### Aðaltilgáta

**Aðaltilgáta** [^01-tilgatuprofun-1] er sú tilgáta sem tilgreinir
einhvers konar mun. Vandamálið er að hún tilgreinir enga fasta tölu sem
hægt er að prófa og því ógerlegt að prófa hana beint. Í okkar dæmi gæti
sannarlega verið munur á launum eftir menntun, en hve mikinn mun ætti að
prófa? Fyrir hvert ár í námi væri hægt að prófa hvort laun hækki um 1kr,
10kr, 15kr, 100kr, 1.000kr, 35.000kr o.s.frv. Tilgátan "það er munur"
hefur ótal möguleika en úrvinnslan krefst þess að við tilgreinum fast
gildi sem hægt er að prófa. Við setjum því fram núlltilgátu.

[^01-tilgatuprofun-1]: Einnig kölluð gagntilgáta, rannsóknartilgáta, (e.
    alternative hypothesis)

### Núlltilgáta

**Núlltilgáta** tilgreinir tiltekið tölugildi, þar sem *ef* það tiltekna
gildi væri í raun rétt -- þá gæti aðaltilgátan ekki líka verið rétt. Í
okkar dæmi yrði núlltilgátan sú að laun séu þau sömu óháð
menntunarstigi. Það er ekki það sama og að segja að *allir séu með sömu
laun* heldur aðeins að ef þú berð saman meðallaun einstaklinga sem hafa
ólíka menntun þá sé munurinn á meðallaunum þeirra = 0 (engin munur á
meðallaunum þeirra sem hafa verið fá ár í skóla og þeirra sem hafa verið
mörg ár í skóla). Ef niðurstaða er sú að núlltilgátan sé sennilega röng
-- þá hlýtur andstæða hennar að vera rétt. M.ö.o. ef munur á launum
eftir menntun er **ekki** núll, þá er jú *einhver* munur og aðaltilgátan
hlýtur því að vera rétt.

------------------------------------------------------------------------

Nú höfum við sett fram tilgátur og næsta skref er að athuga **hvort**
við höfum rétt fyrir okkur -- til þess framkvæmum við marktektarpróf.
