# Marktekt

Við gætum skoðað úrtakstölurnar okkar og séð að í úrtakinu séu meðallaun þeirra sem hafa litla menntun ólík þeirra sem hafa mikla menntun. Tilgangur þess að beita ályktunartölfræði er þó ekki til að *spá fyrir* um úrtakið okkar -- úrtakstölurnar eru jú beint fyrir framan okkur, lýsandi tölfræði myndi því duga til að lýsa þeim. Sá munur sem við sjáum í úrtakinu okkar gæti þó verið tilkominn af hreinni tilviljun. Ímyndum okkur tvö dæmi:

1.  20 manna úrtak þar sem launamunur reynist 10kr á milli þeirra sem hafa háskólamenntun og þeirra sem hafa ekki háskólamenntun. Í þessu úrtaki er vissulega munur en það er einnig auðvelt að ímynda okkur að m.v. úrtakstölur, þá sé í raun engin munur á launum hópana í þýði. Þ.e. þessi 10kr munur endurspeglar bara þá tilviljun sem má búast við þegar við drögum úrtak.
2.  2000 manna úrtak þar sem launamunur reynist 100.000kr á milli hópanna. Hér þætti okkur frekar ólíklegt að svo mikill munur fyndist, af tilviljun, í svo stóru úrtaki **ef það væri í raun engin munur á hópunum í þýði**.

Eftir því sem munurinn er meiri og úrtakið stærra, þeim mun ólíklegra verður að þykja að þessar úrtakstölur séu einskær tilviljun. Þá situr eftir sú spurning -- hversu mikill munur er nógu mikill? Og þá miðað við hversu stórt úrtak? [^02-marktektarprof-1]

[^02-marktektarprof-1]: Ásamt fleiri spurningum sem marktektarpróf taka til greina við útreikning, þetta er einföldun.

Marktektarpróf tekur tillit til ýmissa upplýsinga um úrtakið okkar og athugar líkur þess að fá okkar úrtakstölur **ef þetta úrtak kæmi úr þýði þar sem núlltilgátan er í raun rétt.** *Ef það er í raun **enginn** munur á launum þeirra sem hafa og hafa ekki háskólamenntun, hverjar eru þá líkurnar á því að fá 100.000kr mun í úrtaki með 2.000 manns?*

Ef líkurnar eru mjög litlar, þá ályktum við að það sé ólíklegt að núlltilgátan sé rétt. Ef við náum að hafna núlltilgátunni, þá tökum við upp aðaltilgátuna og ályktum þ.a.l. að það sé í raun munur á hópunum í þýði. Ef líkurnar eru miklar -- t.d. ef niðurstöður segja okkur að það séu 50% líkur á að fá þessar úrtakstölur ef við drógum það af tilviljun úr þýði þar sem það er í raun enginn munur -- þá myndum við hika verulega við að henda fram fullyrðingum.

Næsta spurning er þá -- hversu litlar þurfa líkurnar að vera svo við séum sátt?

------------------------------------------------------------------------

## Marktektarmörk

**Marktektarmörk** ($\alpha$) lýsa því einmitt hvar við drögum línuna, algengast er að miða við við $\alpha$= 0,05. [^02-marktektarprof-2] Þessi tala (0,05) vísar til líkinda (5%) og við erum þá að segja að við viljum að það séu undir 5% líkur á að við höfum rangt fyrir okkur.

[^02-marktektarprof-2]: Undantekningar má t.d. finna í stjarnfræði þar sem við getum ekki tekið jafn mikla sénsa á að hafa rangt fyrir okkur.

## Marktektarpróf

**Marktektarpróf** reikna fyrir okkur líkur þess að fá tilteknar niðurstöður ef núlltilgáta væri í raun rétt og kallar þær *p*-gildi. Ef við höfum ákveðið að draga mörkin við 5% líkindi (0,05) þá munu allar niðurstöður þar sem *p*-gildi er yfir 0,05 þýða að niðurstöður séu ómarktækar. *P* gildi yfir 0,05 þýðir að það séu yfir 5% líkur á að við höfum rangt fyrir okkur og við vorum jú búin að ákveða að draga mörkin við 5%.

Athugum þó að 5% líkur er ekki það sama og 0% líkur. Það er, þó próf sé marktækt, þá *gætum* við haft rangt fyrir okkur. Þannig skoðum aðeins *hvernig* við getum haft rétt eða rangt fyrir okkur með því að gefa okkur eftirfarandi aðstæður í samhengi við dæmið okkar:

|           |                                   |                                  |
|-----------|-----------------------------------|----------------------------------|
|           | Það er ekki munur á launum í þýði | Það er munur á launum í þýði     |
| Marktækt  | Höfnunarmistök (type I error)     | Rétt niðurstaða - Afköst         |
| Ómarktækt | Rétt niðurstaða                   | Fastheldnimistök (type II error) |

: Tafla 1. Niðurstöður marktektarprófs borin saman við raunveruleikann.

## Höfnunarmistök 

**Höfnunarmistök (type I error)** er þegar við gerum þau ***mistök*** að ***hafna*** núlltilgátunni þegar hún er í raun rétt.

Skoðum hólf 1 í töflu 1: Hér er í raun engin munur á launum eftir menntun en niðurstöður okkar eru marktækar. Frá okkar sjónarhorni hugsum við eftirfarandi: *P*-gildi er undir 0,05 --\> próf er marktækt --\> ef próf er marktækt höfnum við núlltilgátunni --\> ef núlltilgátan segir að það sé engin munur, og hún er röng, þá hlýtur að vera munur! --\> við tökum þá upp aðaltilgátu og ályktum að það sé í raun munur á launum eftir menntun.

Hér höfum við gert þau mistök að segja að það sé munur, þegar það er í raun engin munur.

## Fastheldnimistök 

**Fastheldnimistök (type II error)** er þegar við gerum þau ***mistök*** að ***halda í*** núlltilgátu sem er í raun röng.

Skoðum hólf 4 í töflu 1: Hér er í raun munur á launum eftir menntun en niðurstöður okkar eru ómarktækar. Við hugsum því: *P*-gildi er yfir 0,05 --\> prófið er ómarktækt --\> ef próf er ómarktækt þá getum við ekki hafnað núlltilgátunni --\> núlltilgátan segir að það sé engin munur --\> ef ég get ekki hafnað núlltilgátunni, þá get ég ekki tekið upp aðaltilgátuna --\> get ekki sagt að það sé munur á launum eftir menntun.

Hér höfum við gert þau mistök að segja að það sé ekki munur, þegar það er í raun munur.

------------------------------------------------------------------------

**Hvort er verra; að gera höfnunarmistök eða fastheldnimistök?**

Hvorugt er gott en höfnunarmistök eru oft talin valda meiri skaða heldur en fastheldnimistök. Það byggir á þeim rökum að verra sé að hafa rangar upplýsingar heldur en að missa tímabundið af réttum upplýsingum. Það er, betra að segja "ég er ekki viss" heldur en að koma með fullyrðingu sem er röng.

Það eru þó vissulega til aðstæður þar sem fastheldnimistök eru verri. Dæmi um slíkt væri til dæmis ef aukaverkun tiltekins lyfs væri aukin hætta á heilablóðfalli. Í því tilviki myndum við frekar vilja *err on the side of caution*. Við viljum frekar ganga út frá því að þessi hættulega aukaverkun sé raunverulegur möguleiki -- og hafa rangt fyrir okkur -- heldur en að hafa rangt fyrir okkur með því að segja að af lyfinu stafi engin hætta.

Íhugið eftirfarandi fullyrðingar:

-   Þunglyndir eru líklegri til að sýna ofbeldisfulla hegðun.

-   Tiltekið lyf eykur líkur á heilablóðfalli verulega.

-   Hvernig gætum við yfirfært þessi tvö dæmi á fastheldni- og höfnunarmistök? Og hvor mistökin þætti okkur verri í hvoru dæmi fyrir sig?

------------------------------------------------------------------------

## Túlkun ómarktektar 

Hvernig túlkum við ómarktækar niðurstöður? Skoðum hólf 3 í töflu 1, niðurstöður eru ómarktækar og við hugsum; *p*-gildið er yfir 0,05 --\> prófið er því ómarktækt --\> við getum ekki hafnað núlltilgátu --\> getum því ekki tekið upp aðaltilgátu --\> við ályktum að það sé engin munur. Í þessu dæmi vitum við að það er í raun engin munur á launum eftir menntun, svo þessi ákvörðun er rétt.

Við getum þó ekki **staðfest núlltilgátu**, þó við náðum ekki að hafna henni, þá getum við heldur ekki fullyrt að hún sé endilega rétt. Ómarktækar niðurstöður segir bara að *úrtakið okkar* náði ekki að sýna fram á nógu mikinn mun á launum eftir menntun m.t.t. úrtaksstærðar og annarra þátta, upp að því marki að niðurstöður þættu ólíklegar **ef það væri í raun engin munur**.

Fyrir það fyrsta er verulega ólíklegt að núlltilgátan sé virkilega **rétt** (þó við vorum að ímynda okkur slíkar aðstæður í hólfi 3 í töflu 1). Ef núlltilgátan segir að launamunur eftir menntun sé núll, þá þýðir það bókstaflega að munurinn þurfi að vera **núll**. Ekki núll komma eitthvað, ekki næstum því núll, það þyrfti raunverulega að vera **engin** munur. Þriðju breytu áhrif útaf fyrir sig gera það að verkum að það er oft *einhver* fylgni á milli jafnvel ólíklegustu hluta.

Hugsum þetta út frá öðru sjónarhorni: Ef úrtakið okkar nær ekki að sýna fram á mun á milli hópa, þá þýðir það ekki að sá munur sé ekki raunverulega til staðar -- það þýðir **bara** að við náðum ekki að sýna fram á mun. Mögulega þyrfti úrtakið að vera stærra, mældur munur í úrtaki að vera meiri o.s.frv. svo að marktektarprófið væri í stöðu til að yfirhöfuð ná að staðfesta þann mun sem raunverulega er til staðar.

Þessi síðasti punktur leiðir að næstu pælingu, sem er; hversu mikill þarf munurinn að vera og hversu stórt þyrfti úrtakið að vera, svo að marktektarprófið ætti yfirhöfuð séns á að geta sýnt fram á þann mun sem raunverulega er til staðar?

## Afköst

Hingað til höfum við verið að skoða mikið byggt frá því sjónarmiði hvort núlltilgátan sé rétt eða röng. Hér prufum við að snúa þessu við og hugsum dæmið út frá því að við vitum að **aðaltilgátan** sé rétt -- af einhverri ástæðu vitum við fyrir víst að það sé raunverulega munur á launum þeirra sem hafa og hafa ekki lokið háskólamenntun. Afköst eru einmitt hæfni prófs, að gefnum tileknum aðstæðum -- til að geta borið kennsl á þann mun sem er í raun og veru til staðar í þýði.

**Afköst** endurspegla líkur þess að við höfum rétt fyrir okkur þegar aðaltilgátan er rétt (það er í raun munur á hópunum). Við getum þó einnig hugsað um þetta sem líkur þess að gera **ekki fastheldnimistök**. Við getum reiknað afköst í höndunum [^02-marktektarprof-3], með forritlingum á netinu, skoðað sambærilegar rannsóknir og miðað við að finna a.m.k. eins mikið frávik og kemur fram í þeim [^02-marktektarprof-4], eða nota staðlaðar áhrifastærðir [^02-marktektarprof-5]

[^02-marktektarprof-3]: Við ætlum ekki að gera það.

[^02-marktektarprof-4]: Við erum þá að skoða aðrar rannsóknir, þar sem viðfangsefni er svipað og úrtaksstærð er svipuð þeirri sem við ætlum okkur að safna til að fá hugmynd af því hve mikill munurinn er sem við þyrftum að finna til að sýna fram á marktekt.

[^02-marktektarprof-5]: Cohens *d* er dæmi um staðlaða áhrifastærð -- þá er gefið viðmið um það hvaða áhrifastærð telst nógu mikil.

## Loka pælingar um marktekt. 

Þegar hér er komið höfum við framkvæmt marktektarpróf, fengið *p*-gildi og getum þar af leiðandi fjallað um niðurstöður okkar sem marktækar eða ómarktækar. Við erum því hér komin með skýrt svar við spurningunni *er munur á launum eftir menntun?* Gefum okkur nú að prófið okkar sé marktækt og svarið því:

**Marktækur munur fannst á launum fólks eftir menntun þeirra**.

Byggt á þessari staðhæfingu gæti ég hugsað "Glæsilegt -- þannig ef ég mennta mig get ég búist við umtalsvert hærri launum fyrir vikið - annars væru niðurstöður varla marktækar" Eða hvað? Þessi túlkun gæti verið rétt en það eru þó nokkur atriði til að huga að.

"*þannig ef ég mennta mig......*"

-   Marktækar niðurstöður þýða að það sé **að jafnaði** munur á launum hópanna. Það er ekki þar með sagt að þær niðurstöður muni eiga við um **alla** þó hún eigi við **að jafnaði**. Ef við skiptum fólki í tvennt eftir því hvort það hefur háskólamenntun eða ekki þá mætti segja að heilt yfir séu laun þessara hópa ólík. Fyrir tiltekin einstakling er sennilega munur - en ekki endilega.

-   Sambærilegt dæmi væru þær niðurstöður að *"fullorðnir séu að jafnaði hærri en börn*". Við vitum þetta vel en áttum okkur líka á því að það eru vissulega til börn sem eru hærri en margir fullorðnir.

"*...get ég búist við umtalsvert hærri launum fyrir vikið....*"

-   Núlltilgátan okkar var *H0*: meðallaun háskólamenntaðra = meðallaun óháskólamenntaðra. Það er engin munur á launum - þau eru þau sömu fyrir báða hópa.

-   Þær aðaltilgátur sem við prófum geta verið stefnutilgátur (einhliða) eða stefnulausar (tvíhliða). **Stefnulaus** aðaltilgáta segir bara "það er munur" án þess að tilgreina í hvaða átt munurinn er, svo háskólamenntaðir *gætu* þess vegna haft lægri laun. **Stefnutilgáta** tilgreinir hins vegar í hvaða átt munurinn sé og væri þannig að prófa þá tilgátu "háskólamenntaðir hafa hærri laun heldur en óháskólamenntaðir" (eða öfugt).

-   Við þurfum að passa að túlka marktektina í samræmi við þær tilgátur sem voru prófaðar.

"*....annars væru niðurstöður varla marktækar*"

-   Það er alltaf hætta á að við höfum rangt fyrir okkur (séum að gera höfnunarmistök). Annað (en þó tengt) vandamál er að eftir því sem úrtakið er stærra þarf munurinn að vera þeim mun minni svo marktekt náist. Í smáum úrtökum þarf munurinn að vera meiri til að ná marktekt heldur en í stórum úrtökum (líkt og við sáum í dæmi við upphafi marktektarkafla)

Loka pælingin snýr að orðinu *umtalsvert*. Marktekt segir bara **hvort** það sé munur en ekki **hve mikill** hann er - sem tekur okkur í næstu umfjöllun.
