# Tilgátur {#cross}

Við byrjum á því að setja fram **tilgátur**. Í okkar dæmi viljum við vita hvort það sé munur á launum einstaklings eftir menntun viðkomandi.

## Aðaltilgáta

Aðaltilgáta [^02-tilgatur-1] er sú tilgáta sem tilgreinir einhvers konar mun. Vandamálið er að hún tilgreinir enga fasta tölu sem hægt er að prófa og því ógerlegt að prófa hana beint. Í okkar dæmi gæti sannarlega verið munur á launum eftir menntun, en hve mikinn mun ætti að prófa? Fyrir hvert ár í námi væri hægt að prófa hvort laun hækki um 1kr, 10kr, 15kr, 100kr, 1.000kr, 35.000kr o.s.frv. Tilgátan "það er munur" hefur ótal möguleika en úrvinnslan krefst þess að við tilgreinum fast gildi sem hægt er að prófa. Við setjum því fram núlltilgátu.

[^02-tilgatur-1]: Einnig kölluð gagntilgáta, rannsóknartilgáta, (e. alternative hypothesis)

## Núlltilgáta

Núlltilgáta tilgreinir tiltekið tölugildi, þar sem *ef* það tiltekna gildi væri í raun rétt -- þá gæti aðaltilgátan ekki líka verið rétt. Í okkar dæmi yrði núlltilgátan sú að laun séu þau sömu óháð menntunarstigi. Það er ekki það sama og að segja að *allir séu með sömu laun* heldur aðeins að ef þú berð saman meðallaun einstaklinga sem hafa ólíka menntun þá sé munurinn á meðallaunum þeirra = 0 (engin munur á meðallaunum þeirra sem hafa verið fá ár í skóla og þeirra sem hafa verið mörg ár í skóla). Ef niðurstaða er sú að núlltilgátan sé sennilega röng -- þá hlýtur andstæða hennar að vera rétt. M.ö.o. ef munur á launum eftir menntun er **ekki** núll, þá er jú *einhver* munur
og aðaltilgátan hlýtur því að vera rétt.

------------------------------------------------------------------------

Nú höfum við sett fram tilgátur og næsta skref er að athuga **hvort** við höfum rétt fyrir okkur -- til þess framkvæmum við marktektarpróf.
