# Marktekt

Við gætum skoðað úrtakstölurnar okkar og séð að í úrtakinu séu meðallaun þeirra sem hafa litla menntun ólík þeirra sem hafa mikla menntun. Tilgangur þess að beita ályktunartölfræði er þó ekki til að *spá fyrir* um úrtakið okkar -- úrtakstölurnar eru jú beint fyrir framan okkur, lýsandi tölfræði myndi því duga til að lýsa þeim. Sá munur sem við sjáum í úrtakinu okkar gæti þó verið tilkominn af hreinni tilviljun. Ímyndum okkur tvö dæmi:

1.  20 manna úrtak þar sem launamunur reynist 10kr á milli þeirra sem hafa háskólamenntun og þeirra sem hafa ekki háskólamenntun. Í þessu úrtaki er vissulega munur en það er einnig auðvelt að ímynda okkur að m.v. úrtakstölur, þá sé í raun engin munur á launum hópana í þýði. Þ.e. þessi 10kr munur endurspeglar bara þá tilviljun sem má búast við þegar við drögum úrtak.
2.  2000 manna úrtak þar sem launamunur reynist 100.000kr á milli hópanna. Hér þætti okkur frekar ólíklegt að svo mikill munur fyndist, af tilviljun, í svo stóru úrtaki **ef það væri í raun engin munur á hópunum í þýði**.

Eftir því sem munurinn er meiri og úrtakið stærra, þeim mun ólíklegra verður að þykja að þessar úrtakstölur séu einskær tilviljun. Þá situr eftir sú spurning -- hversu mikill munur er nógu mikill? Og þá miðað við hversu stórt úrtak?

Marktektarpróf \^[Ásamt fleiri spurningum sem marktektarpróf tekur til greina við útreikning -- þetta er einföldun.] tekur tillit til ýmissa upplýsinga um úrtakið okkar og athugar líkur þess að fá okkar úrtakstölur **ef þetta úrtak kæmi úr þýði þar sem núlltilgátan er í raun rétt. ** *Ef það er í raun **enginn** munur á launum þeirra sem hafa og hafa ekki háskólamenntun, hverjar eru þá líkurnar á því að fá 100.000kr mun í úrtaki með 2.000 manns?*  

Ef líkurnar eru mjög litlar, þá ályktum við að það sé ólíklegt að núlltilgátan sé rétt. Ef við náum að hafna núlltilgátunni, þá tökum við upp aðaltilgátuna og ályktum þ.a.l. að það sé í raun munur á hópunum í þýði. Ef líkurnar eru miklar -- t.d. ef niðurstöður segja okkur að það séu 50% líkur á að fá þessar úrtakstölur ef við drógum það af tilviljun úr þýði þar sem það er í raun enginn munur -- þá myndum við hika verulega við að henda fram fullyrðingum.

Næsta spurning er þá -- hversu litlar þurfa líkurnar að vera svo við séum sátt?

------------------------------------------------------------------------

**Marktektarmörk** ($\alpha$ ) lýsa því einmitt hvar við drögum línuna, algengast er að miða við við alpha 0,05.\^[Undantekningar má t.d. finna í stjarnfræði þar sem við getum ekki tekið jafn mikla sénsa á að hafa rangt fyrir okkur.] Þessi tala (0,05) vísar til líkinda (5%) og við erum þá að segja að við viljum
að það séu undir 5% líkur á að við höfum rangt fyrir okkur.

**Marktektarpróf** reikna fyrir okkur líkur þess að fá tilteknar niðurstöður ef núlltilgáta væri í raun rétt og kallar þær *p*-gildi. Ef við höfum ákveðið að draga mörkin við 5% líkindi (0,05) þá munu allar niðurstöður þar sem *p*-gildi er yfir 0,05 þýða að niðurstöður séu ómarktækar. *P* gildi yfir 0,05 þýðir að það séu yfir 5% líkur á að við höfum rangt fyrir okkur og við vorum jú búin að ákveða að draga mörkin við 5%.

Athugum þó að 5% líkur (a = 0,05) er ekki það sama og 0% líkur. Það er, þó próf sé marktækt, þá *gætum* við haft rangt fyrir okkur. Þannig skoðum aðeins *hvernig* við getum haft rétt eða rangt fyrir okkur með því að gefa okkur eftirfarandi aðstæður í samhengi við dæmið okkar:

1.  Það er í raun engin munur á launum eftir menntun svo núlltilgáta er rétt.

    1.  Ef niðurstöður okkar eru marktækar þá höfnum við núlltilgátu og tökum upp aðaltilgátu. Við ályktum þá að núlltilgátan sé röng og það sé í raun munur. Þetta kallast **höfnunarmistök** (type 1 error): við gerum þau **mistök** að **hafna** núlltilgátunni þegar hún er í raun rétt.

    2.  Ef niðurstöður okkar eru ómarktækar þá getum við ekki hafnað núlltilgátunni og tökum því ekki upp aðaltilgátuna. Við ályktum að það sé ekki munur á launum hópana og höfum rétt fyrir okkur!

2.  Það er í raun munur á launum eftir menntun svo núlltilgáta er röng.

    1.  Ef niðurstöður okkar eru marktækar þá höfnum við núlltilgátu, tökum upp aðaltilgátu og ályktum að það sé í raun munur. Hér höfum við rétt fyrir okkur -- núlltilgátan er í raun röng (það er munur) -- niðurstöður okkar voru í samræmi við það = við tókum rétta ákvörðun!

    2.  Ef niðurstöður okkar eru ómarktækar þá getum við ekki hafnað núlltilgátu, getum því ekki tekið upp aðaltilgátu og ályktum að það sé ekki munur á launum hópana. Þetta kallast **fastheldnismistök** (type II error): við gerum þau **mistök** að **halda í** núlltilgátu sem er, í
        raun, röng.

------------------------------------------------------------------------

Hvort væri verra, að gera höfnunarmistök eða fastheldnismistök?

Hvorugt er gott en höfnunarmistök eru oft talin valda meiri skaða heldur en fastheldnimistök. Það byggir á þeim rökum að verra sé að hafa rangar upplýsingar heldur en að missa tímabundið af réttum upplýsingum. Það er, betra að segja \"ég er ekki viss\" heldur en að koma með fullyrðingu sem er röng.

Það eru þó vissulega til aðstæður þar sem fastheldnimistök eru verri. Dæmi um slíkt væri til dæmis ef aukaverkun tiltekins lyfs væri aukin hætta á heilablóðfalli. Í því tilviki myndum við frekar vilja *err on the side of caution*. Við viljum frekar ganga út frá því að þessi hættulega aukaverkun sé raunverulegur möguleiki -- og hafa rangt fyrir okkur -- heldur en að hafa rangt fyrir okkur með því að segja að af lyfinu stafi engin hætta.

Gefum okkur að eftirfarandi fullyrðingar:

-   Þunglyndir eru líklegri til að sýna ofbeldisfulla hegðun.

-   Tiltekið lyf eykur líkur á heilablóðfalli verulega.

-   Hvernig gætum við yfirfært þessi tvö dæmi á fastheldni- og höfnunarmistök? Og hvor mistökin þætti okkur verri í hvoru dæmi fyrir sig?

------------------------------------------------------------------------

Hvernig fjöllum við um marktækar eða ómarktækar niðurstöður? Við erum enn að athuga hvort það sé munur á launum eftir menntun, við höfum safnað úrtaki og keyrum marktektarpróf á gögnin.

1.  Ef niðurstöðurnar okkar reynast marktækar, þá höfnum við núlltilgátu og tökum upp aðaltilgátu. Úrtakið okkar sýndi nógu mikinn mun m.t.t. úrtaksstærðar og annarra atriða til að niðurstöðurnar þykja ólíklegar **ef það væri í raun engin munur.** Hér erum við ófeimin við að
    setja fram fullyrðingu þess efnis að það sé í raun munur á launum eftir menntun -- við vorum beinlínis að sýna fram á það.
2.  Ef niðurstöðurnar reynast ómarktækar, þá höfnum við ekki núlltilgátu og getum því ekki tekið upp aðaltilgátu. Úrtakið okkar náði ekki að sýna fram á nógu mikinn mun m.t.t. úrtaksstærðar og annarra atriða til að niðurstöður þættu ólíklegar **ef það væri í raun engin munur**. Hér getum við þó **ekki staðfest núlltilgátu**; þ.e. þó við náðum ekki að hrekja núlltilgátu, þá getum við heldur ekki fullyrt að hún sé endilega rétt.
    1.  Fyrir það fyrsta er verulega ólíklegt að núlltilgátan sé virkilega **rétt**. Ef núlltilgátan spáir því fyrir að launamunur eftir menntun sé núll, þá þýðir það strangt til orða tekið að munurinn
        þurfi að vera **núll**. Ekki núll komma eitthvað, ekki næstum því núll, það þyrfti raunverulega að vera **engin** munur. Þriðju breytu áhrif útaf fyrir sig gera það að verkum að það er oft *einhver* fylgni á milli jafnvel ólíklegustu hluta.

    2.  Að auki þarf að hugsa þetta frá sjónarhorni rökhugsunar. Ef úrtakið okkar nær ekki að sýna fram á mun á milli hópa, þá þýðir það ekki að sá munur sé ekki raunverulega til staðar -- það þýðir **bara** að við náðum ekki að sýna fram á mun. Mögulega þyrfti úrtakið að vera stærra, mældur munur í úrtaki að vera meiri oþh svo að marktektarprófið væri í stöðu til að yfirhöfuð ná að staðfesta þann mun sem raunverulega er til staðar.

Þessi síðasti punktur leiðir að næstu pælingu, sem er; hversu mikill þarf munurinn að vera og hversu stórt þyrfti úrtakið að vera, svo að marktektarprófið ætti yfirhöfuð séns á að geta sýnt fram á þann mun sem raunverulega er til staðar? Hingað til höfum við verið að skoða mikið byggt frá því sjónarmiði hvort núlltilgátan sé rétt eða röng. Hér prufum við að snúa þessu við og hugsum dæmið út frá því að við vitum að **aðaltilgátan** sé rétt -- af einhverri ástæðu vitum við fyrir víst að það sé raunverulega munur á launum þeirra sem hafa og hafa ekki lokið háskólamenntun. Afköst eru einmitt hæfni prófs, að gefnum tileknum aðstæðum -- til að geta borið kennsl á þann mun sem er í raun og veru til staðar í þýði.

Afköst endurspegla líkur þess að við höfum rétt fyrir okkur þegar núlltilgáta er röng (það er í raun munur á hópunum). Við getum þó einnig hugsað um þetta sem líkur þess að gera **ekki fastheldnimistök**. Við getum reiknað afköst í höndunum \^[Við ætlum ekki að gera það.], með forritlingum á netinu, skoðað sambærilegar rannsóknir og miðað við að finna a.m.k. eins mikið frávik og kemur fram í þeim \^[Við erum þá að skoða aðrar rannsóknir, þar sem viðfangsefni er svipað og úrtaksstærð er svipuð þeirri sem við ætlum okkur að safna til að fá hugmynd af því hve
mikill munurinn er sem við þyrftum að finna til að sýna fram á marktekt.], eða nota staðlaðar áhrifastærðir \^[Cohens *d* er dæmi um staðlaða áhrifastærð -- þá er gefið viðmið um það hvaða
áhrifastærð telst nógu mikil. ]

------------------------------------------------------------------------

Að lokum þarf að huga að því að öll marktektarpróf byggja á forsendum sem eru ólíkar eftir því hvaða marktektarpróf um ræðir. Standist forsendur segir það okkur að útreikningur *p*-gilda sé að gefa okkur réttar líkur. Sé forsendubrestur til staðar er hættan sú að *p*-gildið sem fæst sé að of-
eða vanmeta líkindin svo að við getum ekki lengur treyst því að þau alpha mörk sem við ákváðum eigi enn við.

Nú höfum við farið yfir ferlið sem liggur að baki marktektarprófa og hvernig við túlkum *p*-gildið og getum þ.a.l. fjallað um niðurstöður sem marktækar eða ómarktækar. Marktektarpróf eru frábær og gefa okkur skýrt svar við þeirri spurningu sem við erum að leitast svara við. Við erum þannig komin með skýrt svar við spurningunni \"er munur á launum eftir menntun?\".

Gefum okkur nú að svarið sé \"já, það er munur á launum eftir menntun\". Frábært -- það er þó ekki nóg. Marktektarpróf geta sagt okkur **hvort** það sé munur en ekki **hve mikill** sá munur er. Marktækur munur þýðir bara að það sé ólíklegt að hann sé tilkomin af tilviljun en segir ekkert til um hve *merkilegur* sá munur er.

Í launadæminu okkar mætti ímynda sér eftirfarandi niðurstöður:

-   \"Marktækur munur fannst á launum fólks eftir menntun þeirra\". Byggt á þessari staðhæfingu myndi ég hugsa \"flott -- þannig ef ég mennta mig þá mætti ég búast við umtalsvert hærri launum fyrir vikið\" -- eða hvað?

-   Taktu eftir að marktektarprófið var bara að athuga **hvort** það væri munur en var aldrei að reyna að segja til um hvort þessi marktæki munur væri *merkilegur*. Ég myndi því vilja vita \"ok, flott -- launin eru að jafnaði hærri. Ef ég eyði næstu árum í að sækja mér háskólamenntun -- hversu mikið hærri væru launin að jafnaði, í samanburði við launin ef ég myndi ekki sækja mér
    háskólamenntun?\"

-   Raunin gæti verið sú að ef við berum saman þá sem hafa ekki háskólamenntun við þá sem hafa háskólamenntun, þá sé marktækur munur á laununum -- en að sá munur sé að jafnaði aðeins 10.000kr á mánuði. Þrátt fyrir að munurinn sé *marktækur* þá er hann vissulega ekki *merkilegur* -- enda fæstir sem væru til í að lifa við skertar tekjur til fleiri ára, í þeim tilgangi að sækja sér menntun, ef afrakstur þess væri að græða 10.000kr aukalega á mánuði í kjölfarið.

Annað dæmi gæti verið að við fáum marktækar niðurstöður -- aftur þá segir það okkur bara að það sé munur. Við getum athugað muninn sem fæst á launum í úrtakinu okkar og ályktum út frá því að munur á launum er *að jafnaði* 150.000 á mánuði. Þetta eru vissulega merkilegri niðurstöður en þær
sem við fjölluðum um í dæminu á undan, þar sem munur var aðeins 10.000kr á mánuði.

Við vitum þó að ekki **allir** þeir sem hafa háskólamenntun fái ákkurat 150.000kr meira í laun á mánuði -- enda vissulega fleiri þættir sem spila inn í. Pælingin verður því \"hversu mikið gæti þessi tala rokkað til eða frá?\". Þessari pælingu er svarað með öryggisbili.

Ef svarið væri \"munurinn er að jafnaði 150.000kr á mánuði - til eða frá 10.000kr\" þá værum við með frekar þröngt öryggisbil. Það er, m.v. öryggisbilið væri munurinn minnst 140.000kr og mest 160.000 á mánuði.

Væri svarið hins vegar \"munurinn er að jafnaði 150.000kr á mánuði -- til eða frá 120.000kr\" þá værum við með fáranlega breitt öryggisbil. Öryggisbilið væri þá að segja að þó munurinn sé að jafnaði 150.000kr, þá geti hann verið allt frá 10.000kr fyrir suma, en allt upp í 290.000kr fyrir aðra.

Í seinna dæminu er óvissan töluvert meiri og niðurstöðurnar eru í raun að gefa okkur minni upplýsingar heldur en í fyrra dæminu. Seinna dæmið væri í raun að segja \"það gæti verið fínn
munur, hann gæti líka verið mikill, eða enginn -- hver veit?\" Eftir stendur að ef öryggisbilið er mjög vítt, þá erum við litlu nær -- *þrátt fyrir að niðurstöður séu marktækar*.
