# Footnotes and citations

## Footnotes

## Forsendur 

Að lokum þarf að huga að því að öll marktektarpróf byggja á forsendum sem eru ólíkar eftir því hvaða marktektarpróf um ræðir. Standist forsendur segir það okkur að útreikningur *p*-gilda sé að gefa okkur réttar líkur. Sé forsendubrestur til staðar er hættan sú að *p*-gildið sem fæst sé að of- eða vanmeta líkindin svo að við getum ekki lengur treyst því að þau alpha mörk sem við ákváðum eigi enn við.

Jú við gætum búist við hærri tekjum fyrir vikið \^[]

Footnotes are put inside the square brackets after a caret `^[]`. Like this one [^04-citations-1].

[^04-citations-1]: This is a footnote.

## Citations

Reference items in your bibliography file(s) using `@key`.

For example, we are using the **bookdown** package [@R-bookdown] (check out the last code chunk in index.Rmd to see how this citation key was added) in this sample book, which was built on top of R Markdown and **knitr** [@xie2015] (this citation was added manually in an external file book.bib). Note that the `.bib` files need to be listed in the index.Rmd with the YAML `bibliography` key.

The RStudio Visual Markdown Editor can also make it easier to insert citations: <https://rstudio.github.io/visual-markdown-editing/#/citations>
